### ISSUE TITLE
Creating a new custom dynamic positioning controller

### ISSUE THREAD

**Issue by galfunk** [uuvsimulator/uuv_simulator#272]
Hello try to run 
roslaunch uuv_tutorial_dp_controller start_tutorial_dp_controller_demo.launch

the following error appears

[INFO] [1531160226.812975, 0.000000]: Calling service /gazebo/spawn_urdf_model
[rexrov/tutorial_dp_controller-11] process has died [pid 22836, exit code 1, cmd /home/gal/catkin_ws/src/uuv_simulator/uuv_tutorials/uuv_tutorial_dp_controller/scripts/tutorial_dp_controller.py odom:=pose_gt trajectory:=dp_controller/trajectory input_trajectory:=dp_controller/input_trajectory waypoints:=dp_controller/waypoints error:=dp_controller/error reference:=dp_controller/reference thruster_output:=thruster_manager/input_stamped __name:=tutorial_dp_controller __log:=/home/gal/.ros/log/486a11ac-83a4-11e8-ac53-9cb6d0f2f06b/rexrov-tutorial_dp_controller-11.log].
log file: /home/gal/.ros/log/486a11ac-83a4-11e8-ac53-9cb6d0f2f06b/rexrov-tutorial_dp_controller-11*.log

any help??

Many thanks 

Gal

**Comment by musamarcusso** [comment]
Hi @galfunk, could you provide the whole output where this error occurs?

**Comment by galfunk** [comment]
Thank you for your reply, please find the whole output 

gal@gal-XPS-15-9560:~$ roslaunch eca_a9_gazebo start_demo_teleop.launch joy_id:=0
... logging to /home/gal/.ros/log/ba51bd2c-83d8-11e8-ac53-9cb6d0f2f06b/roslaunch-gal-XPS-15-9560-19453.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

redefining global property: gamma
when processing file: /home/gal/catkin/src/eca_a9/eca_a9_description/urdf/eca_a9_sensors.xacro
included from: /home/gal/catkin/src/eca_a9/eca_a9_description/robots/eca_a9_default.urdf.xacro
started roslaunch server http://gal-XPS-15-9560:45909/

SUMMARY
========

PARAMETERS
 * /eca_a9/finned_uuv_teleop/axis_pitch: 4
 * /eca_a9/finned_uuv_teleop/axis_roll: 0
 * /eca_a9/finned_uuv_teleop/axis_thruster: 1
 * /eca_a9/finned_uuv_teleop/axis_yaw: 3
 * /eca_a9/finned_uuv_teleop/fin_topic_prefix: fins/
 * /eca_a9/finned_uuv_teleop/fin_topic_suffix: /input
 * /eca_a9/finned_uuv_teleop/gain_pitch: [1, 1, -1, -1]
 * /eca_a9/finned_uuv_teleop/gain_roll: [1, 1, 1, 1]
 * /eca_a9/finned_uuv_teleop/gain_yaw: [-1, 1, 1, -1]
 * /eca_a9/finned_uuv_teleop/n_fins: 4
 * /eca_a9/finned_uuv_teleop/thruster_joy_gain: -1.0
 * /eca_a9/finned_uuv_teleop/thruster_model/max_thrust: 5
 * /eca_a9/finned_uuv_teleop/thruster_model/name: proportional
 * /eca_a9/finned_uuv_teleop/thruster_model/params/gain: 4.9e-05
 * /eca_a9/finned_uuv_teleop/thruster_topic: thrusters/0/input
 * /eca_a9/joystick/autorepeat_rate: 10
 * /eca_a9/joystick/dev: /dev/input/js0
 * /eca_a9/robot_description: <?xml version="1....
 * /eca_a9/robot_state_publisher/publish_frequency: 5
 * /eca_a9/robot_state_publisher/robot_description: /eca_a9/robot_des...
 * /ground_truth_to_tf_eca_a9/child_frame_id: /eca_a9/base_link
 * /ground_truth_to_tf_eca_a9/footprint_frame_id: /eca_a9/base_foot...
 * /ground_truth_to_tf_eca_a9/frame_id: /world
 * /ground_truth_to_tf_eca_a9/odometry_topic: /eca_a9/pose_gt
 * /ground_truth_to_tf_eca_a9/stabilized_frame_id: /eca_a9/base_stab...
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /eca_a9/
    finned_uuv_teleop (uuv_teleop/finned_uuv_teleop.py)
    joystick (joy/joy_node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    urdf_spawner (uuv_descriptions/spawn_model.py)
  /
    ground_truth_to_tf_eca_a9 (message_to_tf/message_to_tf)
    recording (rosbag/record)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[eca_a9/urdf_spawner-1]: started with pid [19474]
process[eca_a9/robot_state_publisher-2]: started with pid [19475]
process[ground_truth_to_tf_eca_a9-3]: started with pid [19476]
process[eca_a9/finned_uuv_teleop-4]: started with pid [19483]
process[eca_a9/joystick-5]: started with pid [19500]
[ WARN] [1531182762.513436604]: The root link eca_a9/base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
process[rviz-6]: started with pid [19524]
process[recording-7]: started with pid [19536]
[ INFO] [1531182762.725779339]: rviz version 1.12.16
[ INFO] [1531182762.725864979]: compiled against Qt version 5.5.1
[ INFO] [1531182762.725880571]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1531182762.937683709]: Stereo is NOT SUPPORTED
[ INFO] [1531182762.937769415]: OpenGl version: 3 (GLSL 1.3).
spawn_model script started
starting FinnedUUVControllerNode.py
[INFO] [1531182763.627752, 0.000000]: Loading model xml from ros parameter
[INFO] [1531182763.638986, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1531182763.640382, 0.000000]: Calling service /gazebo/spawn_urdf_model
FinnedUUVControllerNode: initializing node
Thruster #0 - proportional - thrusters/0/input
[INFO] [1531182763.711138, 12.544000]: Thruster model:
[INFO] [1531182763.711601, 12.544000]: 	Gain=4.9e-05
QMetaObject::invokeMethod: No such method QMenuBar::aboutToShow()
[INFO] [1531182764.314355, 12.604000]: Spawn status: SpawnModel: Successfully spawned entity
[eca_a9/urdf_spawner-1] process has finished cleanly
log file: /home/gal/.ros/log/ba51bd2c-83d8-11e8-ac53-9cb6d0f2f06b/eca_a9-urdf_spawner-1*.log
^C[recording-7] killing on exit
[rviz-6] killing on exit
[eca_a9/joystick-5] killing on exit
[eca_a9/finned_uuv_teleop-4] killing on exit
[ground_truth_to_tf_eca_a9-3] killing on exit
[eca_a9/robot_state_publisher-2] killing on exit
exiting
shutting down processing monitor...
... shutting down processing monitor complete
done
gal@gal-XPS-15-9560:~$ roslaunch uuv_tutorial_dp_controller start_tutorial_dp_controller_demo.launch
... logging to /home/gal/.ros/log/ae609832-8421-11e8-ac53-9cb6d0f2f06b/roslaunch-gal-XPS-15-9560-22284.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://gal-XPS-15-9560:43655/

SUMMARY
========

PARAMETERS
 * /publish_world_models/meshes/east/plane: [2000, 0.1, 100]
 * /publish_world_models/meshes/east/pose/position: [0, 1000, -50]
 * /publish_world_models/meshes/heightmap/mesh: package://uuv_des...
 * /publish_world_models/meshes/heightmap/model: sand_heightmap
 * /publish_world_models/meshes/north/plane: [0.1, 2000, 100]
 * /publish_world_models/meshes/north/pose/position: [1000, 0, -50]
 * /publish_world_models/meshes/seafloor/plane: [2000, 2000, 0.1]
 * /publish_world_models/meshes/seafloor/pose/position: [0, 0, -100]
 * /publish_world_models/meshes/south/plane: [0.1, 2000, 100]
 * /publish_world_models/meshes/south/pose/position: [-1000, 0, -50]
 * /publish_world_models/meshes/west/plane: [2000, 0.1, 100]
 * /publish_world_models/meshes/west/pose/position: [0, -1000, -50]
 * /rexrov/ground_truth_to_tf_rexrov/child_frame_id: /rexrov/base_link
 * /rexrov/ground_truth_to_tf_rexrov/footprint_frame_id: /rexrov/base_foot...
 * /rexrov/ground_truth_to_tf_rexrov/frame_id: world
 * /rexrov/ground_truth_to_tf_rexrov/odometry_topic: /rexrov/pose_gt
 * /rexrov/ground_truth_to_tf_rexrov/stabilized_frame_id: /rexrov/base_stab...
 * /rexrov/robot_description: <?xml version="1....
 * /rexrov/robot_state_publisher/publish_frequency: 5
 * /rexrov/robot_state_publisher/robot_description: /rexrov/robot_des...
 * /rexrov/thruster_allocator/tam: [[0.1597426884844...
 * /rexrov/thruster_manager/base_link: base_link
 * /rexrov/thruster_manager/conversion_fcn: proportional
 * /rexrov/thruster_manager/conversion_fcn_params/gain: 0.00031
 * /rexrov/thruster_manager/max_thrust: 2000.0
 * /rexrov/thruster_manager/tf_prefix: rexrov
 * /rexrov/thruster_manager/thruster_frame_base: thruster_
 * /rexrov/thruster_manager/thruster_topic_prefix: thrusters/
 * /rexrov/thruster_manager/thruster_topic_suffix: /input
 * /rexrov/thruster_manager/timeout: -1
 * /rexrov/thruster_manager/update_rate: 50
 * /rexrov/tutorial_dp_controller/Kd: [9077.459, 9077.4...
 * /rexrov/tutorial_dp_controller/Ki: [321.417, 321.417...
 * /rexrov/tutorial_dp_controller/Kp: [11993.888, 11993...
 * /rexrov/tutorial_dp_controller/saturation: 5000
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /use_sim_time: True

NODES
  /rexrov/
    ground_truth_to_tf_rexrov (message_to_tf/message_to_tf)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    thruster_allocator (uuv_thruster_manager/thruster_allocator.py)
    trajectory_marker_publisher (uuv_control_utils/trajectory_marker_publisher.py)
    tutorial_dp_controller (uuv_tutorial_dp_controller/tutorial_dp_controller.py)
    urdf_spawner (uuv_descriptions/spawn_model.py)
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    publish_world_models (uuv_assistants/publish_world_models.py)
    rviz (rviz/rviz)
    world_ned_frame_publisher (tf2_ros/static_transform_publisher)

auto-starting new master
process[master]: started with pid [22297]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ae609832-8421-11e8-ac53-9cb6d0f2f06b
process[rosout-1]: started with pid [22310]
started core service [/rosout]
process[gazebo-2]: started with pid [22334]
process[gazebo_gui-3]: started with pid [22339]
process[world_ned_frame_publisher-4]: started with pid [22344]
process[publish_world_models-5]: started with pid [22345]
process[rexrov/urdf_spawner-6]: started with pid [22363]
process[rexrov/robot_state_publisher-7]: started with pid [22364]
process[rexrov/ground_truth_to_tf_rexrov-8]: started with pid [22365]
process[rexrov/thruster_allocator-9]: started with pid [22369]
process[rexrov/trajectory_marker_publisher-10]: started with pid [22389]
[ WARN] [1531214084.212068035]: The root link rexrov/base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
process[rexrov/tutorial_dp_controller-11]: started with pid [22402]
process[rviz-12]: started with pid [22419]
Gazebo multi-robot simulator, version 7.13.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1531214084.390509735]: rviz version 1.12.16
[ INFO] [1531214084.390633650]: compiled against Qt version 5.5.1
[ INFO] [1531214084.390698695]: compiled against OGRE version 1.9.0 (Ghadamon)
Gazebo multi-robot simulator, version 7.13.1
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[ INFO] [1531214084.508542233]: Finished loading Gazebo ROS API Plugin.
[Msg] Waiting for master.
[ INFO] [1531214084.510832545]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1531214084.510907500]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1531214084.511264186]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.1.104
[Msg] Publicized address: 192.168.1.104
libGL error: failed to create drawable
[ INFO] [1531214084.548975861]: Stereo is NOT SUPPORTED
[ INFO] [1531214084.549330075]: OpenGl version: 3 (GLSL 1.3).
Warning [parser.cc:527] Can not find the XML attribute 'version' in sdf XML tag for model: NED frame. Please specify the SDF protocol supported in the model configuration file. The first sdf tag in the config file will be used 
Start publishing vehicle footprints to RViz
spawn_model script started
Traceback (most recent call last):
  File "/home/gal/catkin_ws/src/uuv_simulator/uuv_tutorials/uuv_tutorial_dp_controller/scripts/tutorial_dp_controller.py", line 24, in <module>
    from uuv_control_interfaces import DPControllerBase
  File "/home/gal/catkin_ws/devel/lib/python2.7/dist-packages/uuv_control_interfaces/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 17, in <module>
  File "/home/gal/catkin_ws/src/uuv_simulator/uuv_control/uuv_trajectory_control/src/uuv_control_interfaces/sym_vehicle.py", line 17, in <module>
    import casadi
ImportError: No module named casadi
Starting trajectory and waypoint marker publisher
[INFO] [1531214085.012968, 0.000000]: Loading model xml from ros parameter
[INFO] [1531214085.019945, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1531214085.022564, 0.000000]: Calling service /gazebo/spawn_urdf_model
New model being published: north
	 Position: [1000, 0, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: west
	 Position: [0, -1000, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
[rexrov/tutorial_dp_controller-11] process has died [pid 22402, exit code 1, cmd /home/gal/catkin_ws/src/uuv_simulator/uuv_tutorials/uuv_tutorial_dp_controller/scripts/tutorial_dp_controller.py odom:=pose_gt trajectory:=dp_controller/trajectory input_trajectory:=dp_controller/input_trajectory waypoints:=dp_controller/waypoints error:=dp_controller/error reference:=dp_controller/reference thruster_output:=thruster_manager/input_stamped __name:=tutorial_dp_controller __log:=/home/gal/.ros/log/ae609832-8421-11e8-ac53-9cb6d0f2f06b/rexrov-tutorial_dp_controller-11.log].
log file: /home/gal/.ros/log/ae609832-8421-11e8-ac53-9cb6d0f2f06b/rexrov-tutorial_dp_controller-11*.log
[Msg] Loading underwater world...
[Msg] Current velocity [m/s] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = 0
	Max. Limit = 5
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity horizontal angle [rad] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = -3.14159
	Max. Limit = 3.14159
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity horizontal angle [rad] Gauss-Markov process model:
[Msg] 	Mean = 0
	Min. Limit = -3.14159
	Max. Limit = 3.14159
	Mu = 0
	Noise Amp. = 0
[Msg] Current velocity topic name: hydrodynamics/current_velocity
[Msg] Underwater current plugin loaded!
	WARNING: Current velocity calculated in the ENU frame
[Msg] UnderwaterCurrentROSPlugin::namespace=hydrodynamics
[Msg] Spherical coordinates reference=
	- Latitude [degrees]=56.719
	- Longitude [degrees]=3.51562
	- Altitude [m]=0
[ INFO] [1531214085.757114258, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1531214085.761678920, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[ INFO] [1531214085.763210487, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1531214085.766085596, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[ INFO] [1531214085.769018009, 0.002000000]: Camera Plugin: Using the 'robotNamespace' param: '/rexrov/'
[ INFO] [1531214085.774254845, 0.002000000]: Camera Plugin (ns = /rexrov/)  <tf_prefix_>, set to "/rexrov"
[Msg] GPSROSPlugin - Loading base sensor plugin
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
[INFO] [1531214085.861134, 0.002000]: Spawn status: SpawnModel: Successfully spawned entity
[Msg] GPSROSPlugin - Converting GPS sensor pointer
[Msg] GPSROSPlugin - Initialize sensor topic publisher
New model being published: heightmap
	 Position: [0.0, 0.0, -95.0]
	 Orientation: [0.0, 0.0, 0.0, 1.0]
	 Scale: [1, 1, 1]
New model being published: seafloor
	 Position: [0, 0, -100]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: east
	 Position: [0, 1000, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
New model being published: south
	 Position: [-1000, 0, -50]
	 Orientation: [0, 0, 0, 1]
	 Scale: [1, 1, 1]
Registered HydrodynamicModel type fossen
Registered HydrodynamicModel type sphere
Registered HydrodynamicModel type cylinder
Registered HydrodynamicModel type spheroid
Registered HydrodynamicModel type box
[Msg] Subscribing to current velocity topic: hydrodynamics/current_velocity
[Msg] Name of the BASE_LINK: rexrov/base_link
[Msg] New bounding box for rexrov/base_link::Min[-0.75 -1.3 -0.8] Max[0.75 1.3 0.8]
[Msg] HMFossen: Using linear damping for forward speed NULL
rexrov::rexrov/base_link::added_mass
      779.79     -6.8773     -103.32      8.5426     -165.54     -7.8033
     -6.8773        1222       51.29      409.44     -5.8488      62.726
     -103.32       51.29      3659.9      6.1112     -386.42      10.774
      8.5426      409.44      6.1112       534.9     -10.027      21.019
     -165.54     -5.8488     -386.42     -10.027      842.69     -1.1162
     -7.8033      62.726      10.775      21.019     -1.1162      224.32
rexrov::rexrov/base_link::scaling_added_mass
rexrov::rexrov/base_link::offset_added_mass
rexrov::rexrov/base_link::linear_damping
      -74.82           0           0           0           0           0
           0      -69.48           0           0           0           0
           0           0      -728.4           0           0           0
           0           0           0      -268.8           0           0
           0           0           0           0     -309.77           0
           0           0           0           0           0        -105
rexrov::rexrov/base_link::linear_damping_forward_speed
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
           0           0           0           0           0           0
rexrov::rexrov/base_link::quadratic_damping
     -748.22           0           0           0           0           0
           0     -992.53           0           0           0           0
           0           0    -1821.01           0           0           0
           0           0           0        -672           0           0
           0           0           0           0     -774.44           0
           0           0           0           0           0     -523.27
rexrov::rexrov/base_link::scaling_damping
rexrov::rexrov/base_link::offset_linear_damping
rexrov::rexrov/base_link::offset_lin_forward_speed_damping
rexrov::rexrov/base_link::offset_nonlin_damping
rexrov::rexrov/base_link::volume
     1.83826 m^3
rexrov::rexrov/base_link::scaling_volume
Registered ThrusterDynamics type ZeroOrder
Registered ThrusterDynamics type FirstOrder
Registered ThrusterDynamics type Yoerger
Registered ThrusterDynamics type Bessa
Registered ConversionFunction type Basic
Registered ConversionFunction type Bessa
Registered ConversionFunction type LinearInterp
[Msg] Thruster #0 initialized
	- Link: rexrov/thruster_0
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/0/input
	- Thrust output topic: /rexrov/thrusters/0/thrust
[Msg] Thruster #1 initialized
	- Link: rexrov/thruster_1
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/1/input
	- Thrust output topic: /rexrov/thrusters/1/thrust
[Msg] Thruster #2 initialized
	- Link: rexrov/thruster_2
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/2/input
	- Thrust output topic: /rexrov/thrusters/2/thrust
[Msg] Thruster #3 initialized
	- Link: rexrov/thruster_3
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/3/input
	- Thrust output topic: /rexrov/thrusters/3/thrust
[Msg] Thruster #4 initialized
	- Link: rexrov/thruster_4
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/4/input
	- Thrust output topic: /rexrov/thrusters/4/thrust
[Msg] Thruster #5 initialized
	- Link: rexrov/thruster_5
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/5/input
	- Thrust output topic: /rexrov/thrusters/5/thrust
[Msg] Thruster #6 initialized
	- Link: rexrov/thruster_6
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/6/input
	- Thrust output topic: /rexrov/thrusters/6/thrust
[Msg] Thruster #7 initialized
	- Link: rexrov/thruster_7
	- Robot model: rexrov
	- Input command topic: /rexrov/thrusters/7/input
	- Thrust output topic: /rexrov/thrusters/7/thrust
[Msg] Static reference frame=world
[Msg] Static reference frame=ssbl
[Msg] Static reference frame=world
[Msg] Static reference frame=world
[Msg] JointStatePublisher::robotNamespace=rexrov
[Msg] JointStatePublisher::Retrieving moving joints:
[Msg] 	- rexrov/thruster_0_joint
[Msg] 	- rexrov/thruster_1_joint
[Msg] 	- rexrov/thruster_2_joint
[Msg] 	- rexrov/thruster_3_joint
[Msg] 	- rexrov/thruster_4_joint
[Msg] 	- rexrov/thruster_5_joint
[Msg] 	- rexrov/thruster_6_joint
[Msg] 	- rexrov/thruster_7_joint
[ INFO] [1531214086.114005819, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[rexrov/urdf_spawner-6] process has finished cleanly
log file: /home/gal/.ros/log/ae609832-8421-11e8-ac53-9cb6d0f2f06b/rexrov-urdf_spawner-6*.log
[ INFO] [1531214086.114257199, 0.022000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1531214086.144043, 0.052000]: base_link transform NED to ENU=
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -1.00000000e+00  -1.22464680e-16]
 [  0.00000000e+00   1.22464680e-16  -1.00000000e+00]]
[INFO] [1531214086.144318, 0.052000]: ThrusterManager::update_rate=50
Thruster #0 - proportional - thrusters/0/input
[INFO] [1531214086.155829, 0.064000]: Thruster model:
[INFO] [1531214086.156126, 0.064000]: 	Gain=0.00031
Thruster #1 - proportional - thrusters/1/input
[INFO] [1531214086.158391, 0.066000]: Thruster model:
[INFO] [1531214086.158679, 0.066000]: 	Gain=0.00031
Thruster #2 - proportional - thrusters/2/input
[INFO] [1531214086.160860, 0.068000]: Thruster model:
[INFO] [1531214086.161113, 0.068000]: 	Gain=0.00031
Thruster #3 - proportional - thrusters/3/input
[INFO] [1531214086.163442, 0.070000]: Thruster model:
[INFO] [1531214086.163951, 0.072000]: 	Gain=0.00031
Thruster #4 - proportional - thrusters/4/input
[INFO] [1531214086.165860, 0.072000]: Thruster model:
[INFO] [1531214086.166357, 0.074000]: 	Gain=0.00031
Thruster #5 - proportional - thrusters/5/input
[INFO] [1531214086.169637, 0.076000]: Thruster model:
[INFO] [1531214086.170002, 0.078000]: 	Gain=0.00031
Thruster #6 - proportional - thrusters/6/input
[INFO] [1531214086.172792, 0.080000]: Thruster model:
[INFO] [1531214086.173075, 0.080000]: 	Gain=0.00031
Thruster #7 - proportional - thrusters/7/input
[INFO] [1531214086.175534, 0.082000]: Thruster model:
[INFO] [1531214086.175823, 0.082000]: 	Gain=0.00031
[INFO] [1531214086.176189, 0.084000]: Thruster allocation matrix provided!
[INFO] [1531214086.176417, 0.084000]: TAM=
[INFO] [1531214086.177788, 0.084000]: [[ 0.15974269  0.15974269 -0.15974243 -0.15974243  0.70710686  0.70710686
  -0.70710654 -0.70710654]
 [-0.21361012  0.21361012 -0.21360977  0.21360977  0.7071067  -0.7071067
   0.70710702 -0.70710702]
 [ 0.9637702   0.9637702   0.96377032  0.96377032  0.          0.          0.
   0.        ]
 [ 0.43523203 -0.43523203  0.43523188 -0.43523188 -0.09121676  0.09121676
  -0.09121681  0.09121681]
 [ 0.9430935   0.9430935  -0.94309347 -0.94309347  0.09121679  0.09121679
  -0.09121674 -0.09121674]
 [ 0.13688862 -0.13688862 -0.1368884   0.1368884  -0.64879876  0.64879876
   0.64879873 -0.64879873]]
[ INFO] [1531214086.179505844, 0.086000000]: Physics dynamic reconfigure ready.
[INFO] [1531214086.181852, 0.088000]: TAM provided, skipping...
[INFO] [1531214086.182160, 0.088000]: ThrusterManager: ready
[INFO] [1531214086.182757, 0.090000]: Invalid output directory for the TAM matrix, dir=None
[INFO] [1531214086.183083, 0.090000]: ThrusterManager: ready
[ INFO] [1531214086.183410703, 0.090000000]: Physics dynamic reconfigure ready.
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.
[Wrn] [msgs.cc:1808] Conversion of sensor type[gps] not suppported.

**Comment by musamarcusso** [comment]
Hi @galfunk, thanks for the information.
It seems that you are missing `casadi` in your system. This is part of a new implementation but it shouldn't affect other controllers. I will fix this to enforce the use of this package to be optional.
If you want to fix this now, you can install `casadi` using 

```
sudo pip install casadi
```

**Comment by galfunk** [comment]
Thanks

**Comment by galfunk** [comment]
I have another question regarding the option to generate a ROS bag with the recorded simulated data, if I set the flag "true", where the location of the recorded bag file define ?

Thanks again

**Comment by galfunk** [comment]
I try to install the casadi - unfortunately received sudo: pip: command not found

**Comment by musamarcusso** [comment]
For `pip`: to install `pip` you have to run 

```
sudo apt install python-pip
```

In the tutorial I forgot to put the option to determine the path to the `recording.bag` file. Per default it should be stored in your `$HOME/.ros` folder. If you check the [`record.launch` file](https://github.com/uuvsimulator/uuv_simulator/blob/master/uuv_gazebo/launch/controller_demos/record_demo.launch#L3), you should be able to see the argument `bag_filename` with the full path for the ROS bag. I will add option this to the tutorial, though.
