### ISSUE TITLE
Error, trying launch start_demo_nmb_sm.launch in both lauv and eca_a9. 

### ISSUE THREAD

**Issue by liqsuq** [uuvsimulator/uuv_simulator#373]
I will try to launch start_demo_nmb_sm.launch after I succeed start_demo_auv_control.launch and start_demo_teleop.launch.

I launch world fine, but I got following error  when I launched start_demo_nmb_sm.launch.

Maybe the main cause is start_control_allocator.launch and invalid "output_dir" arg...
I couldn't know how I should modify. 

~~~
$ roslaunch eca_a9_gazebo start_demo_nmb_sm.launch 
... logging to /home/redhawk/.ros/log/251a3ff2-c966-11e9-8c40-14feb5ee288b/roslaunch-t5500-16592.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
redefining global property: gamma
when processing file: /opt/ros/melodic/share/eca_a9_description/urdf/eca_a9_sensors.xacro
included from: /opt/ros/melodic/share/eca_a9_description/robots/eca_a9_default.urdf.xacro
started roslaunch server http://t5500:36429/

SUMMARY
========

PARAMETERS
 * /eca_a9/control_allocator/base_link: base_link
 * /eca_a9/control_allocator/fin_config/fin_area: 0.04155
 * /eca_a9/control_allocator/fin_config/fluid_density: 1028.0
 * /eca_a9/control_allocator/fin_config/frame_base: fin
 * /eca_a9/control_allocator/fin_config/lift_coefficient: 3.0
 * /eca_a9/control_allocator/fin_config/lower_limit: -1.4
 * /eca_a9/control_allocator/fin_config/topic_prefix: fins
 * /eca_a9/control_allocator/fin_config/topic_suffix: input
 * /eca_a9/control_allocator/fin_config/upper_limit: 1.4
 * /eca_a9/control_allocator/output_dir: /opt/ros/melodic/...
 * /eca_a9/control_allocator/thruster_config/conversion_fcn: proportional
 * /eca_a9/control_allocator/thruster_config/conversion_fcn_params/gain: 4.9e-05
 * /eca_a9/control_allocator/thruster_config/conversion_fcn_params/input: [0, 1, 2, 3]
 * /eca_a9/control_allocator/thruster_config/conversion_fcn_params/output: [0, 1, 2, 3]
 * /eca_a9/control_allocator/thruster_config/frame_base: thruster_
 * /eca_a9/control_allocator/thruster_config/max_thrust: 700
 * /eca_a9/control_allocator/thruster_config/topic_prefix: thrusters
 * /eca_a9/control_allocator/thruster_config/topic_suffix: input
 * /eca_a9/control_allocator/timeout: -1
 * /eca_a9/control_allocator/update_rate: 10
 * /eca_a9/ground_truth_to_tf_eca_a9/child_frame_id: /eca_a9/base_link
 * /eca_a9/ground_truth_to_tf_eca_a9/footprint_frame_id: /eca_a9/base_foot...
 * /eca_a9/ground_truth_to_tf_eca_a9/frame_id: world
 * /eca_a9/ground_truth_to_tf_eca_a9/odometry_topic: /eca_a9/pose_gt
 * /eca_a9/ground_truth_to_tf_eca_a9/stabilized_frame_id: /eca_a9/base_stab...
 * /eca_a9/robot_description: <?xml version="1....
 * /eca_a9/robot_state_publisher/robot_description: /eca_a9/robot_des...
 * /eca_a9/rov_nmb_sm_controller/Kd: [24.3289994058185...
 * /eca_a9/rov_nmb_sm_controller/Ki: [0.00102327681525...
 * /eca_a9/rov_nmb_sm_controller/dubins/max_pitch: 0.09
 * /eca_a9/rov_nmb_sm_controller/dubins/radius: 25
 * /eca_a9/rov_nmb_sm_controller/inertial_frame_id: world
 * /eca_a9/rov_nmb_sm_controller/look_ahead_delay: 2.0
 * /eca_a9/rov_nmb_sm_controller/max_forward_speed: 3.0
 * /eca_a9/rov_nmb_sm_controller/min_thrust: 40
 * /eca_a9/rov_nmb_sm_controller/saturation: 200
 * /eca_a9/rov_nmb_sm_controller/slope: [0.99038586689920...
 * /eca_a9/rov_nmb_sm_controller/thrusters_only: False
 * /eca_a9/rov_nmb_sm_controller/use_stamped_poses_only: False
 * /eca_a9/send_waypoint_file/filename: /opt/ros/melodic/...
 * /eca_a9/send_waypoint_file/interpolator: dubins
 * /eca_a9/send_waypoint_file/start_time: -1
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /eca_a9/
    control_allocator (uuv_auv_control_allocator/control_allocator)
    ground_truth_to_tf_eca_a9 (uuv_assistants/uuv_message_to_tf)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rov_nmb_sm_controller (uuv_trajectory_control/rov_nmb_sm_controller.py)
    send_waypoint_file (uuv_control_utils/send_waypoint_file.py)
    trajectory_marker_publisher (uuv_control_utils/trajectory_marker_publisher.py)
    urdf_spawner (uuv_descriptions/spawn_model)
  /
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[eca_a9/urdf_spawner-1]: started with pid [16614]
process[eca_a9/robot_state_publisher-2]: started with pid [16615]
process[eca_a9/ground_truth_to_tf_eca_a9-3]: started with pid [16616]
process[eca_a9/trajectory_marker_publisher-4]: started with pid [16617]
process[eca_a9/control_allocator-5]: started with pid [16623]
process[eca_a9/rov_nmb_sm_controller-6]: started with pid [16628]
[ WARN] [1566977629.644545370]: The root link eca_a9/base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
process[rviz-7]: started with pid [16630]
process[eca_a9/send_waypoint_file-8]: started with pid [16631]
[ INFO] [1566977629.792964638]: rviz version 1.13.3
[ INFO] [1566977629.793011827]: compiled against Qt version 5.9.5
[ INFO] [1566977629.793021862]: compiled against OGRE version 1.9.0 (Ghadamon)
[INFO] [1566977630.062148, 0.000000]: Send a waypoint file, namespace=/eca_a9/
[ERROR] [1566977630.065250, 0.000000]: Negative start time, setting it to 0.0
[INFO] [1566977630.066003, 0.000000]: Start time=0.00 s
spawn_model script started
Starting trajectory and waypoint marker publisher
Starting Non-model-based Sliding Mode Controller
[INFO] [1566977630.431977, 0.000000]: Initialize control allocator for vehicle <eca_a9>
[INFO] [1566977630.438364, 0.000000]: Lookup transfrom from eca_a9/base_link_ned to eca_a9/base_link
[INFO] [1566977630.465867, 0.000000]: Loading model xml from ros parameter
[INFO] [1566977630.471704, 0.000000]: Using the ENU coordinates to spawn the model
[INFO] [1566977630.472504, 0.000000]: Initial position wrt the world frame: (0.00, 0.00, -20.00)
[INFO] [1566977630.473467, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[INFO] [1566977630.476310, 0.000000]: Calling service /gazebo/spawn_urdf_model
No transform found between base_link and base_link_ned for vehicle eca_a9
"eca_a9/base_link" passed to lookupTransform argument target_frame does not exist. 
[INFO] [1566977630.513424, 12.470000]: ControlAllocator: updating thruster poses
[INFO] [1566977630.514411, 12.480000]: Lookup: Thruster transform found eca_a9/base_link -> eca_a9/thruster_0
ECA_A9 -- 2019-08-28 16:33:50,561 | INFO | dp_controller_base | Setting controller as non-model-based
ECA_A9 -- 2019-08-28 16:33:50,563 | INFO | wp_trajectory_generator | Waypoint interpolators available:
ECA_A9 -- 2019-08-28 16:33:50,563 | INFO | wp_trajectory_generator | 	 - cubic
ECA_A9 -- 2019-08-28 16:33:50,563 | INFO | wp_trajectory_generator | 	 - lipb
ECA_A9 -- 2019-08-28 16:33:50,563 | INFO | wp_trajectory_generator | 	 - dubins
ECA_A9 -- 2019-08-28 16:33:50,564 | INFO | wp_trajectory_generator | 	 - linear
ECA_A9 -- 2019-08-28 16:33:50,564 | INFO | dp_controller_local_planner | Max. forward speed [m/s]=3.00
ECA_A9 -- 2019-08-28 16:33:50,565 | INFO | dp_controller_local_planner | Idle circle radius [m] = 10.00
ECA_A9 -- 2019-08-28 16:33:50,567 | INFO | dp_controller_local_planner | Inertial frame ID=world
ECA_A9 -- 2019-08-28 16:33:50,628 | INFO | dp_controller_local_planner | Transform world_ned (NED) to world (ENU)=
[[ -3.74939946e-33   1.00000000e+00   1.22464680e-16]
 [  1.00000000e+00  -4.44089210e-16  -2.46519033e-32]
 [  0.00000000e+00   1.22464680e-16  -1.00000000e+00]]
ECA_A9 -- 2019-08-28 16:33:50,628 | INFO | dp_controller_local_planner | Inertial frame ID=world
ECA_A9 -- 2019-08-28 16:33:50,628 | INFO | dp_controller_local_planner | Max. forward speed = 3.0
ECA_A9 -- 2019-08-28 16:33:50,629 | INFO | dp_controller_local_planner | No parameters for interpolation method <cubic> found
ECA_A9 -- 2019-08-28 16:33:50,630 | INFO | dp_controller_local_planner | No parameters for interpolation method <lipb> found
ECA_A9 -- 2019-08-28 16:33:50,631 | INFO | dp_controller_local_planner | Parameters for interpolation method <dubins> found
ECA_A9 -- 2019-08-28 16:33:50,631 | INFO | dp_controller_local_planner | 	{'radius': 25, 'max_pitch': 0.09}
ECA_A9 -- 2019-08-28 16:33:50,632 | INFO | dp_controller_local_planner | No parameters for interpolation method <linear> found
Transform world_ned (NED) to world (ENU)=
[[ -3.74939946e-33   1.00000000e+00   1.22464680e-16]
 [  1.00000000e+00  -4.44089210e-16  -2.46519033e-32]
 [  0.00000000e+00   1.22464680e-16  -1.00000000e+00]]
ECA_A9 -- 2019-08-28 16:33:50,672 | INFO | dp_controller_base | DP controller successfully initialized
ECA_A9 -- 2019-08-28 16:33:50,672 | ERROR | dp_controller_local_planner | Invalid waypoint file
ECA_A9 -- 2019-08-28 16:33:50,672 | INFO | rov_nmb_sm_controller | Initializing: Model-free Sliding Mode Controller
[INFO] [1566977630.672965, 12.630000]: Waypoints file successfully received, filename=/opt/ros/melodic/share/eca_a9_gazebo/config/waypoint_set.yaml
ECA_A9 -- 2019-08-28 16:33:50,673 | INFO | rov_nmb_sm_controller | K=[ 0.  0.  0.  0.  0.  0.]
ECA_A9 -- 2019-08-28 16:33:50,674 | INFO | rov_nmb_sm_controller | Kd=[ 24.32899941  95.16574837  25.94337741   0.           6.38837136
  79.28449769]
ECA_A9 -- 2019-08-28 16:33:50,676 | INFO | rov_nmb_sm_controller | Ki=[ 0.00102328  0.00102328  0.00102328  0.          0.11901644  0.11901644]
ECA_A9 -- 2019-08-28 16:33:50,677 | INFO | rov_nmb_sm_controller | slope=[ 0.99038587  0.99038587  0.99038587  0.          0.20796466  0.20796466]
ECA_A9 -- 2019-08-28 16:33:50,678 | INFO | rov_nmb_sm_controller | Saturation limits=0.8
ECA_A9 -- 2019-08-28 16:33:50,680 | INFO | rov_nmb_sm_controller | Model-free Sliding Mode Controller ready
[eca_a9/send_waypoint_file-8] process has finished cleanly
log file: /home/redhawk/.ros/log/251a3ff2-c966-11e9-8c40-14feb5ee288b/eca_a9-send_waypoint_file-8*.log
[INFO] [1566977631.170134, 12.630000]: Spawn status: SpawnModel: Successfully spawned entity
[eca_a9/urdf_spawner-1] process has finished cleanly
log file: /home/redhawk/.ros/log/251a3ff2-c966-11e9-8c40-14feb5ee288b/eca_a9-urdf_spawner-1*.log
[ INFO] [1566977631.438122854, 12.650000000]: Stereo is NOT SUPPORTED
[ INFO] [1566977631.438882147, 12.650000000]: OpenGl version: 4.3 (GLSL 4.3).
ECA_A9 -- 2019-08-28 16:33:51,467 | INFO | wp_trajectory_generator | Interpolation method set: lipb
ECA_A9 -- 2019-08-28 16:33:51,467 | INFO | dp_controller_local_planner | AUTOMATIC MODE = OFF
[INFO] [1566977631.767679, 12.980000]: Thruster transform found eca_a9/base_link -> eca_a9/thruster_0
[INFO] [1566977631.769040, 12.980000]: pos=[-0.9676  0.      0.    ]
[INFO] [1566977631.770571, 12.980000]: rot=[  0.00000000e+00   0.00000000e+00   1.00000000e+00  -1.03411554e-13]
Thruster #0 - proportional - /eca_a9/thrusters/0/input
[INFO] [1566977631.773615, 12.980000]: Thruster model:
[INFO] [1566977631.774785, 12.980000]: 	Gain=4.9e-05
[INFO] [1566977631.775638, 12.980000]: Lookup: Fin transform found eca_a9/base_link -> eca_a9/fin0
[INFO] [1566977631.776578, 12.980000]: Fin transform found eca_a9/base_link -> eca_a9/fin0
[INFO] [1566977631.777876, 12.990000]: pos=[-0.70777  -0.07876   0.078586]
[INFO] [1566977631.778866, 12.990000]: quat=[ 0.38172247 -0.06525197 -0.02702841  0.92157452]
[INFO] [1566977631.781473, 12.990000]: Lookup: Fin transform found eca_a9/base_link -> eca_a9/fin1
[INFO] [1566977631.782582, 12.990000]: Fin transform found eca_a9/base_link -> eca_a9/fin1
[INFO] [1566977631.783746, 12.990000]: pos=[-0.70777  -0.07876  -0.078586]
[INFO] [1566977631.784713, 12.990000]: quat=[ 0.92157593 -0.02702865 -0.06525187  0.38171908]
[INFO] [1566977631.787280, 13.000000]: Lookup: Fin transform found eca_a9/base_link -> eca_a9/fin2
[INFO] [1566977631.788744, 13.000000]: Fin transform found eca_a9/base_link -> eca_a9/fin2
[INFO] [1566977631.790005, 13.000000]: pos=[-0.70777   0.07876  -0.078586]
[INFO] [1566977631.791069, 13.000000]: quat=[ 0.92157593  0.02702865 -0.06525187 -0.38171908]
[INFO] [1566977631.793453, 13.000000]: Lookup: Fin transform found eca_a9/base_link -> eca_a9/fin3
[INFO] [1566977631.794550, 13.000000]: Fin transform found eca_a9/base_link -> eca_a9/fin3
[INFO] [1566977631.795865, 13.000000]: pos=[-0.70777   0.07876   0.078586]
[INFO] [1566977631.797687, 13.010000]: quat=[-0.38172247 -0.06525197  0.02702841  0.92157452]
[INFO] [1566977631.799975, 13.010000]: # fins found: 4
[INFO] [1566977631.800933, 13.010000]: 0
[INFO] [1566977631.801877, 13.010000]: [-0.70777  -0.07876   0.078586]
[INFO] [1566977631.803532, 13.010000]: [[  9.90023291e-01   1.09102283e-06  -1.40903812e-01]
 [ -9.96336682e-02   7.07114847e-01  -7.00044088e-01]
 [  9.96344138e-02   7.07098715e-01   7.00060277e-01]]
[INFO] [1566977631.805376, 13.010000]: 1
[INFO] [1566977631.806331, 13.010000]: [-0.70777  -0.07876  -0.078586]
[INFO] [1566977631.808072, 13.020000]: [[  9.90023291e-01  -2.12617265e-06  -1.40903812e-01]
 [ -9.96336682e-02  -7.07119990e-01  -7.00038893e-01]
 [ -9.96344138e-02   7.07093572e-01  -7.00065471e-01]]
[INFO] [1566977631.809907, 13.020000]: 2
[INFO] [1566977631.810956, 13.020000]: [-0.70777   0.07876  -0.078586]
[INFO] [1566977631.812712, 13.020000]: [[  9.90023291e-01   2.12617265e-06  -1.40903812e-01]
 [  9.96336682e-02  -7.07119990e-01   7.00038893e-01]
 [ -9.96344138e-02  -7.07093572e-01  -7.00065471e-01]]
[INFO] [1566977631.814817, 13.020000]: 3
[INFO] [1566977631.816082, 13.020000]: [-0.70777   0.07876   0.078586]
[INFO] [1566977631.818481, 13.030000]: [[  9.90023291e-01  -1.09102283e-06  -1.40903812e-01]
 [  9.96336682e-02   7.07114847e-01   7.00044088e-01]
 [  9.96344138e-02  -7.07098715e-01   7.00060277e-01]]
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/uuv_auv_control_allocator/control_allocator", line 144, in <module>
    node = AUVControlAllocator()
  File "/opt/ros/melodic/lib/uuv_auv_control_allocator/control_allocator", line 36, in __init__
    'Invalid output directory, output_dir=' + self.output_dir)
rospy.exceptions.ROSException: Invalid output directory, output_dir=/opt/ros/melodic/share/eca_a9_control/config
[eca_a9/control_allocator-5] process has died [pid 16623, exit code 1, cmd /opt/ros/melodic/lib/uuv_auv_control_allocator/control_allocator control_input:=control_allocation/control_input __name:=control_allocator __log:=/home/redhawk/.ros/log/251a3ff2-c966-11e9-8c40-14feb5ee288b/eca_a9-control_allocator-5.log].
log file: /home/redhawk/.ros/log/251a3ff2-c966-11e9-8c40-14feb5ee288b/eca_a9-control_allocator-5*.log
ECA_A9 -- 2019-08-28 16:33:56,418 | INFO | dp_controller_local_planner | AUV STATION KEEPING
ECA_A9 -- 2019-08-28 16:33:56,421 | INFO | dp_controller_local_planner | STATION KEEPING MODE = ON
ECA_A9 -- 2019-08-28 16:33:56,422 | INFO | wp_trajectory_generator | Interpolation method set: cubic
[INFO] [1566977636.422591, 17.630000]: Initial rotation vector (quat)=[  2.47666258e-16   5.72008794e-04   7.81617178e-17   9.99999836e-01]
[INFO] [1566977636.423790, 17.630000]: Initial rotation vector (rpy)=(4.954221773422383e-16, 0.0011440176496412247, 1.5660684712437678e-16)
[INFO] [1566977636.425483, 17.630000]: PathGenerator::Setting initial rotation as=[  2.47666258e-16   5.72008794e-04   7.81617178e-17   9.99999836e-01]
ECA_A9 -- 2019-08-28 16:33:56,426 | INFO | wp_trajectory_generator | Setting new starting time, t=17.63 s
ECA_A9 -- 2019-08-28 16:33:56,426 | ERROR | dp_controller_local_planner | Error generating trajectory message
ECA_A9 -- 2019-08-28 16:33:56,426 | INFO | dp_controller_local_planner | STATION KEEPING MODE = OFF
ECA_A9 -- 2019-08-28 16:33:56,426 | INFO | dp_controller_local_planner | AUTOMATIC MODE = ON
ECA_A9 -- 2019-08-28 16:33:56,426 | INFO | dp_controller_local_planner | TRAJECTORY TRACKING = ON
ECA_A9 -- 2019-08-28 16:33:56,473 | INFO | wp_trajectory_generator | Waypoint interpolator initialized! Start time: 17.63 s
ECA_A9 -- 2019-08-28 16:34:22,626 | INFO | dp_controller_local_planner | /eca_a9/ - Trajectory completed!
ECA_A9 -- 2019-08-28 16:34:22,626 | INFO | dp_controller_local_planner | STATION KEEPING MODE = ON
ECA_A9 -- 2019-08-28 16:34:22,626 | INFO | dp_controller_local_planner | AUTOMATIC MODE = OFF
ECA_A9 -- 2019-08-28 16:34:22,627 | INFO | dp_controller_local_planner | TRAJECTORY TRACKING = OFF
ECA_A9 -- 2019-08-28 16:34:27,674 | INFO | dp_controller_local_planner | AUV STATION KEEPING
ECA_A9 -- 2019-08-28 16:34:27,676 | INFO | dp_controller_local_planner | STATION KEEPING MODE = ON
ECA_A9 -- 2019-08-28 16:34:27,677 | INFO | wp_trajectory_generator | Interpolation method set: cubic
[INFO] [1566977667.677558, 48.880000]: Initial rotation vector (quat)=[  8.38085085e-17   1.85375118e-03   3.75953978e-16   9.99998282e-01]
[INFO] [1566977667.678610, 48.880000]: Initial rotation vector (rpy)=(1.6901174083154135e-16, 0.0037075044800792237, 7.522225537474225e-16)
[INFO] [1566977667.680376, 48.880000]: PathGenerator::Setting initial rotation as=[  8.38085085e-17   1.85375118e-03   3.75953978e-16   9.99998282e-01]
ECA_A9 -- 2019-08-28 16:34:27,681 | INFO | wp_trajectory_generator | Setting new starting time, t=48.88 s
ECA_A9 -- 2019-08-28 16:34:28,216 | INFO | dp_controller_local_planner | Updating the trajectory information
ECA_A9 -- 2019-08-28 16:34:28,216 | INFO | dp_controller_local_planner | STATION KEEPING MODE = OFF
ECA_A9 -- 2019-08-28 16:34:28,216 | INFO | dp_controller_local_planner | AUTOMATIC MODE = ON
ECA_A9 -- 2019-08-28 16:34:28,216 | INFO | dp_controller_local_planner | TRAJECTORY TRACKING = ON
ECA_A9 -- 2019-08-28 16:34:28,222 | INFO | wp_trajectory_generator | Waypoint interpolator initialized! Start time: 48.88 s
~~~

any help?

**Comment by liqsuq** [comment]
The model is certainly spawn, but not be controlled, only floating to the surface.

**Comment by wee-flame** [comment]
I also faced the situation. when I run roslaunch eca_a9_gazebo start_demo_nmb_sm.launch .The eca_a9 did not be controlled, only floating to the surface. Have you solved this problem?
